In [2]:
%matplotlib inline
#loading and storing training data
import numpy as np
from matplotlib import pyplot as plt
fhand =open("trainX.txt")
Train_data=np.loadtxt("trainX.txt",dtype=int)
print(Train_data)
print(Train_data.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(500, 256)


In [3]:
#storng data of digit 2
two_train=Train_data[:250,:]
row1=two_train[0]
#printing image of digit 2
img=np.reshape(row1,(16,16),order="F")
plt.imshow(img)

In [11]:
#computing probabilities of digit 2
two_one_prob=(two_train.sum(axis=0)+1)/(two_train.shape[0]+2)
two_zero_prob=1-two_one_prob
print(two_one_prob)
print(two_zero_prob)

[0.01190476 0.03571429 0.07142857 0.10714286 0.09126984 0.07539683
 0.04365079 0.01984127 0.01190476 0.00793651 0.01587302 0.02777778
 0.03571429 0.05952381 0.05555556 0.02380952 0.03571429 0.1031746
 0.13095238 0.13492063 0.11111111 0.09126984 0.03174603 0.00396825
 0.00396825 0.00793651 0.02777778 0.04365079 0.09126984 0.11507937
 0.14285714 0.07936508 0.09920635 0.21031746 0.23015873 0.1984127
 0.1547619  0.0952381  0.03571429 0.01587302 0.00396825 0.01587302
 0.05952381 0.11111111 0.20634921 0.27777778 0.29761905 0.23412698
 0.23412698 0.32142857 0.28968254 0.21428571 0.13492063 0.05555556
 0.03174603 0.01190476 0.00793651 0.01984127 0.0952381  0.1547619
 0.29761905 0.38095238 0.33333333 0.33333333 0.37698413 0.32539683
 0.21428571 0.17063492 0.09126984 0.03968254 0.01984127 0.00793651
 0.00396825 0.04365079 0.12698413 0.24603175 0.37301587 0.50396825
 0.43253968 0.39285714 0.55555556 0.35714286 0.23015873 0.1468254
 0.06349206 0.02380952 0.00396825 0.00793651 0.03174603 0.07539683

In [12]:
#storing data and computing probability of digit 4
four_train=Train_data[250::]
four_one_prob=(four_train.sum(axis=0)+1)/(four_train.shape[0]+2)
four_zero_prob=1-four_one_prob
print(four_one_prob)
print(four_zero_prob)

[0.01587302 0.01587302 0.01587302 0.01587302 0.01984127 0.01984127
 0.02380952 0.03571429 0.04365079 0.0515873  0.04365079 0.03174603
 0.01190476 0.01190476 0.00793651 0.00396825 0.0515873  0.0515873
 0.05952381 0.05952381 0.05555556 0.04761905 0.06746032 0.06349206
 0.07936508 0.07142857 0.09126984 0.08730159 0.01587302 0.00793651
 0.00793651 0.00793651 0.08333333 0.09126984 0.1031746  0.13095238
 0.13888889 0.1547619  0.15079365 0.15873016 0.17460317 0.1984127
 0.17063492 0.13095238 0.07142857 0.03174603 0.01190476 0.00396825
 0.20238095 0.22619048 0.21825397 0.23809524 0.26984127 0.3015873
 0.3015873  0.3531746  0.3452381  0.36111111 0.28571429 0.21428571
 0.08730159 0.03968254 0.00793651 0.00396825 0.18253968 0.16269841
 0.16666667 0.21031746 0.21825397 0.26587302 0.33730159 0.39285714
 0.33730159 0.33333333 0.3015873  0.21825397 0.09126984 0.03571429
 0.01984127 0.02777778 0.20634921 0.20238095 0.20634921 0.22619048
 0.21825397 0.28968254 0.24206349 0.26984127 0.26190476 0.2738095

In [13]:
#printing image of digit 4
row250=four_train[0]
img4=np.reshape(row250,(16,16),order="F")
plt.imshow(img4)

In [14]:
#loading testing data
Test_data=np.loadtxt("testX.txt",dtype=int)
print(Test_data)
print(Test_data.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(100, 256)


In [20]:
#computing probability and storing predicted results
result=[]
sum2=0
sum4=0
for row in Test_data:
    count=0
    mul=1
    for digit in row:
        if(digit==1):
            mul*=two_one_prob[count]
        else:
            mul*=two_zero_prob[count]
        count+=1
    count1=0
    mul1=1
    for digit in row:
        if(digit==1):
            mul1*=four_one_prob[count1]
        else:
            mul1*=four_zero_prob[count1]
        count1+=1
    mul/=2
    mul1/=2
    if(mul>mul1):
        sum2+=1
        print("It is digit 2")
        result.append(2)
    else:
        sum4+=1
        print("It is digit 4")
        result.append(4)

It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 2
It is digit 4
It is digit 4
It is digit 4
It is digit 4
It is digit 4
It is digit 4
It is digit 4
It is digit 4
It is digit 4
It is digit 4
It is digit 4
It is digit 4
It is digit 4
It is digit 4
It is digit 4
It is digit 4
It is digit 4
It is digit 4
It is digit 4
It is digit 4
It is digit 4
It is 

In [28]:
#caluclating accuracy and precision of system
test=np.loadtxt("testY.txt",dtype=int)
Tp=0
Tn=0
Fp=0
Fn=0
count=0
while (count<100):
    if(test[count]==result[count]):
        if(test[count]==2):
            Tp+=1
        elif(test[count]==4):
            Tn+=1
    else:
        if(test[count]==2):
            Fn+=1
        else:
            Fp+=1
    count+=1
accuracy=(Tp+Tn)/(Tp+Tn+Fn+Fp)
precision=(Tp)/(Tp+Fp)
print("Accuarcy :",accuracy)
print("Precision :",precision)

Accuarcy : 1.0
Precision : 1.0
